# Generated by Django 5.0.1 on 2024-02-23 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('display_name', models.CharField(max_length=125)),
                ('first_name', models.CharField(blank=True, max_length=125, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=125, null=True)),
                ('last_name', models.CharField(blank=True, max_length=125, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
